/* ============================================================
   PROMPT-FORGE v2  |  Data layer
   99 video/shot commands + 9 anatomy sections (bilingual chips)
   ============================================================ */

/* ---- 1) Shot / video command groups ------------------------ */
const COMMANDS = [
  { id:'g1', icon:'🎬', fa:'دستورهای دوربین و حرکت', en:'Camera & Movement',
    items:[
      { cmd:'/cinematic',   fa:'شات ویدیویی سینمایی و حرفه‌ای',   en:'Cinematic professional shot', anim:'a-cinematic' },
      { cmd:'/droneview',   fa:'نمای هوایی از بالا مثل پهپاد',    en:'Aerial drone view from above', anim:'a-droneview' },
      { cmd:'/closeup',     fa:'نمای نزدیک و پرجزئیات',           en:'Close-up with high detail', anim:'a-closeup' },
      { cmd:'/wideangle',   fa:'نمای باز و گسترده با عمق بیشتر',  en:'Wide-angle expansive view', anim:'a-wideangle' },
      { cmd:'/orbit',       fa:'چرخش روان دور سوژه',              en:'Smooth orbit around subject', anim:'a-orbit' },
      { cmd:'/dollyin',     fa:'نزدیک شدن دوربین به سوژه',        en:'Dolly in toward subject', anim:'a-dollyin' },
      { cmd:'/dollyout',    fa:'عقب رفتن دوربین از سوژه',         en:'Dolly out from subject', anim:'a-dollyout' },
      { cmd:'/tracking',    fa:'دنبال کردن سوژه حین حرکت',        en:'Tracking moving subject', anim:'a-tracking' },
      { cmd:'/slowmotion',  fa:'صحنه آهسته با جزئیات بیشتر',      en:'Slow motion detail shot', anim:'a-slowmotion' },
      { cmd:'/timelapse',   fa:'تایم‌لپس با گذر سریع زمان',        en:'Timelapse, fast time passage', anim:'a-timelapse' },
      { cmd:'/hyperlapse',  fa:'حرکت سریع دوربین، دینامیک بالا',  en:'Hyperlapse fast dynamic move', anim:'a-hyperlapse' },
    ]},
  { id:'g2', icon:'📐', fa:'زاویه‌های حرفه‌ای دوربین', en:'Pro Camera Angles',
    items:[
      { cmd:'/lowangle',       fa:'نمای از پایین برای حس قدرت',   en:'Low angle, powerful feel', anim:'a-lowangle' },
      { cmd:'/highangle',      fa:'نمای از بالا برای دید گسترده', en:'High angle wide view', anim:'a-highangle' },
      { cmd:'/overhead',       fa:'نمای کاملاً عمودی از بالا',     en:'Overhead top-down view', anim:'a-overhead' },
      { cmd:'/pov',            fa:'نمای اول‌شخص از چشم سوژه',     en:'POV first-person view', anim:'a-pov' },
      { cmd:'/overtheshoulder',fa:'نمای از پشت شانه + محیط',      en:'Over the shoulder shot', anim:'a-OTS' },
      { cmd:'/establishing',   fa:'نمای معرفی صحنه و مکان',       en:'Establishing shot', anim:'a-establishing' },
      { cmd:'/rackfocus',      fa:'تغییر فوکوس نرم بین سوژه‌ها',  en:'Rack focus between subjects', anim:'a-rackfocus' },
      { cmd:'/handheld',       fa:'حرکت دوربین دستی و طبیعی',     en:'Handheld natural motion', anim:'a-handheld' },
      { cmd:'/steadicam',      fa:'حرکت نرم و پایدار دوربین',     en:'Steadicam smooth shot', anim:'a-steadicam' },
      { cmd:'/craneup',        fa:'حرکت رو به بالا سینمایی',      en:'Crane up cinematic move', anim:'a-craneup' },
      { cmd:'/cranedown',      fa:'حرکت رو به پایین، نمای گسترده',en:'Crane down wide reveal', anim:'a-cranedown' },
    ]},
  { id:'g3', icon:'🏃', fa:'دستورهای حرکت و اکشن', en:'Motion & Action',
    items:[
      { cmd:'/running',    fa:'دویدن با حس سرعت و انرژی',     en:'Running with speed energy', anim:'a-running' },
      { cmd:'/walking',    fa:'راه رفتن طبیعی و واقعی',       en:'Natural walking', anim:'a-walking' },
      { cmd:'/turnaround', fa:'چرخش روان ۳۶۰ درجه دور سوژه', en:'360 turnaround around subject', anim:'a-turnaround' },
      { cmd:'/reveal',     fa:'نمایش تدریجی سوژه یا صحنه',   en:'Gradual reveal', anim:'a-reveal' },
      { cmd:'/entrance',   fa:'ورود سینمایی شخصیت به صحنه',  en:'Cinematic character entrance', anim:'a-entrance' },
      { cmd:'/exit',       fa:'خروج سینمایی از صحنه',         en:'Cinematic exit', anim:'a-exit' },
      { cmd:'/freeze',     fa:'فریز کردن حرکت در لحظه خاص',  en:'Freeze frame moment', anim:'a-freeze' },
      { cmd:'/speedramp',  fa:'ترکیب حرکت آهسته و سریع',     en:'Slow-to-fast speed ramp', anim:'a-speedramp' },
      { cmd:'/bullettime', fa:'افکت آهسته سبک Bullet Time',  en:'Bullet Time slow effect', anim:'a-bullettime' },
      { cmd:'/floating',   fa:'حس شناور بودن در فضا',        en:'Floating in space', anim:'a-floating' },
      { cmd:'/falling',    fa:'صحنه سقوط دراماتیک',          en:'Dramatic falling', anim:'a-falling' },
    ]},
  { id:'g4', icon:'💡', fa:'نورپردازی سینمایی', en:'Cinematic Lighting',
    items:[
      { cmd:'/goldenhour', fa:'نور گرم ساعت طلایی',        en:'Golden hour warm light', anim:'a-goldenhour' },
      { cmd:'/bluehour',   fa:'نور سرد و آرام گرگ‌ومیش',    en:'Blue hour twilight', anim:'a-bluehour' },
      { cmd:'/neonlight',  fa:'نور نئونی سینمایی و زنده',  en:'Vivid neon lighting', anim:'a-neonlight' },
      { cmd:'/moody',      fa:'نور تیره و دراماتیک',       en:'Moody dramatic lighting', anim:'a-moody' },
      { cmd:'/softlight',  fa:'نور نرم و پخش‌شده استودیو', en:'Soft diffused studio light', anim:'a-softlight' },
      { cmd:'/rimlight',   fa:'نور حاشیه‌ای دور سوژه',     en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/silhouette', fa:'نمای قدرتمند سیلوئت',       en:'Strong silhouette', anim:'a-silhouette' },
      { cmd:'/spotlight',  fa:'نور متمرکز روی سوژه',       en:'Focused spotlight', anim:'a-spotlight' },
      { cmd:'/volumetric', fa:'پرتوهای حجمی اتمسفریک',     en:'Volumetric light beams', anim:'a-volumetric' },
      { cmd:'/backlight',  fa:'نور قوی از پشت سوژه',       en:'Strong backlight', anim:'a-backlight' },
      { cmd:'/nightscene', fa:'صحنه شب سینمایی و واقعی',   en:'Cinematic night scene', anim:'a-nightscene' },
    ]},
  { id:'g5', icon:'🖼️', fa:'ترکیب‌بندی و کادربندی', en:'Composition & Framing',
    items:[
      { cmd:'/wide',          fa:'کادر باز برای نمایش کامل صحنه',  en:'Wide full-scene frame', anim:'a-wide' },
      { cmd:'/tight',         fa:'کادر بسته برای تمرکز روی سوژه',  en:'Tight subject-focused frame', anim:'a-tight' },
      { cmd:'/minimal',       fa:'ترکیب‌بندی ساده و مینیمال',      en:'Minimal composition', anim:'a-minimal' },
      { cmd:'/leadinglines',  fa:'خطوط هدایت‌گر نگاه',             en:'Leading lines', anim:'a-leadinglines' },
      { cmd:'/ruleofthirds',  fa:'قانون یک‌سوم، کادر متعادل',       en:'Rule of thirds balance', anim:'a-ruleofthirds' },
      { cmd:'/symmetry',      fa:'ترکیب‌بندی متقارن',              en:'Symmetrical composition', anim:'a-symmetry' },
      { cmd:'/foreground',    fa:'پیش‌زمینه قوی برای عمق بیشتر',   en:'Strong foreground depth', anim:'a-foreground' },
      { cmd:'/framewithinframe', fa:'قاب طبیعی درون صحنه',         en:'Frame within a frame', anim:'a-framewithinframe' },
      { cmd:'/diagonal',      fa:'ترکیب‌بندی مورب و پویا',         en:'Diagonal dynamic composition', anim:'a-diagonal' },
      { cmd:'/centered',      fa:'قرارگیری سوژه در مرکز',          en:'Centered subject', anim:'a-centered' },
      { cmd:'/negativespace', fa:'استفاده مؤثر از فضای منفی',      en:'Effective negative space', anim:'a-negativespace' },
    ]},
  { id:'g6', icon:'✨', fa:'افکت‌های دوربین', en:'Camera Effects',
    items:[
      { cmd:'/motionblur', fa:'محوشدگی حرکت برای حس سرعت',  en:'Motion blur for speed', anim:'a-motionblur' },
      { cmd:'/zoomblur',   fa:'محوشدگی زوم دراماتیک',       en:'Dramatic zoom blur', anim:'a-zoomblur' },
      { cmd:'/bokeh',      fa:'بوکه در پس‌زمینه',           en:'Background bokeh', anim:'a-bokeh' },
      { cmd:'/lensflare',  fa:'فلر سینمایی لنز',            en:'Cinematic lens flare', anim:'a-lensflare' },
      { cmd:'/vignette',   fa:'تیره‌کردن لبه‌های تصویر',     en:'Vignette dark edges', anim:'a-vignette' },
      { cmd:'/splittone',  fa:'درجه‌بندی رنگی دوگانه',      en:'Split-tone grading', anim:'a-splittone' },
      { cmd:'/monochrome', fa:'تبدیل صحنه به سیاه‌وسفید',   en:'Monochrome black & white', anim:'a-monochrome' },
      { cmd:'/radialblur', fa:'محوشدگی شعاعی و پویا',       en:'Radial blur', anim:'a-radialblur' },
      { cmd:'/prism',      fa:'شکست نور منشوری',            en:'Prism light refraction', anim:'a-prism' },
      { cmd:'/glitch',     fa:'افکت گلیچ دیجیتال',          en:'Digital glitch effect', anim:'a-glitch' },
      { cmd:'/filmgrain',  fa:'دانه‌های فیلم با حس قدیمی',   en:'Vintage film grain', anim:'a-filmgrain' },
    ]},
  { id:'g7', icon:'🔍', fa:'فوکوس و عمق میدان', en:'Focus & Depth of Field',
    items:[
      { cmd:'/macro',         fa:'جزئیات بسیار نزدیک',          en:'Extreme macro detail', anim:'a-macro' },
      { cmd:'/shallowdepth',  fa:'عمق میدان کم',               en:'Shallow depth of field', anim:'a-shallowdepth' },
      { cmd:'/deepfocus',     fa:'وضوح پیش و پس‌زمینه',        en:'Deep focus, all sharp', anim:'a-deepfocus' },
      { cmd:'/selectivefocus',fa:'فوکوس روی سوژه، محو شدن اطراف',en:'Selective focus', anim:'a-selectivefocus' },
      { cmd:'/eyefocus',      fa:'فوکوس دقیق روی چشم‌ها',      en:'Sharp eye focus', anim:'a-eyefocus' },
      { cmd:'/centerfocus',   fa:'وضوح مرکز، محو شدن اطراف',   en:'Center focus, soft edges', anim:'a-centerfocus' },
      { cmd:'/tunnelfocus',   fa:'فوکوس تونلی برای جلب توجه',  en:'Tunnel focus', anim:'a-tunnelfocus' },
      { cmd:'/focusstack',    fa:'ترکیب چند فوکوس برای وضوح',  en:'Focus stacking sharpness', anim:'a-focusstack' },
      { cmd:'/dropfocus',     fa:'فوکوس روی قطره یا جزء خاص',  en:'Focus on a droplet detail', anim:'a-dropfocus' },
      { cmd:'/manualfocus',   fa:'کنترل دستی فوکوس',           en:'Manual focus control', anim:'a-manualfocus' },
      { cmd:'/bokehshape',    fa:'شکل‌دهی سفارشی نورهای بوکه', en:'Custom-shaped bokeh', anim:'a-bokehshape' },
    ]},
  { id:'g8', icon:'🎨', fa:'اصلاح و درجه‌بندی رنگ', en:'Color Correction & Grading',
    items:[
      { cmd:'/warm',        fa:'تن‌های گرم برای حس صمیمی',  en:'Warm tones, cozy feel', anim:'a-warm' },
      { cmd:'/cool',        fa:'تن‌های سرد برای حس آرام',   en:'Cool tones, calm feel', anim:'a-cool' },
      { cmd:'/contrast',    fa:'افزایش کنتراست تصویر',      en:'Increased contrast', anim:'a-contrast' },
      { cmd:'/exposure',    fa:'تنظیم روشنایی و نوردهی',    en:'Exposure adjustment', anim:'a-exposure' },
      { cmd:'/saturation',  fa:'افزایش یا کاهش غلظت رنگ',   en:'Color saturation control', anim:'a-saturation' },
      { cmd:'/desaturate',  fa:'کاهش رنگ برای ظاهر خنثی',   en:'Desaturated neutral look', anim:'a-desaturate' },
      { cmd:'/cinematic',   fa:'درجه‌بندی رنگ سینمایی',     en:'Cinematic color grading', anim:'a-cinematicgrade' },
      { cmd:'/tealorange',  fa:'رنگ‌بندی فیروزه‌ای و نارنجی',en:'Teal & orange grade', anim:'a-tealorange' },
      { cmd:'/vibrant',     fa:'تقویت رنگ‌ها، تصویر زنده‌تر',en:'Vibrant boosted colors', anim:'a-vibrant' },
      { cmd:'/bw',          fa:'تبدیل به سیاه‌وسفید',       en:'Black & white', anim:'a-bw' },
      { cmd:'/neon',        fa:'درجه‌بندی رنگ نئونی',       en:'Neon color grade', anim:'a-neon' },
    ]},
  { id:'g9', icon:'🧑‍🎤', fa:'پرتره و سوژه', en:'Portrait & Subject',
    items:[
      { cmd:'/portrait',       fa:'نمای پرتره',                   en:'Portrait shot', anim:'a-portrait' },
      { cmd:'/beauty',         fa:'تقویت زیبایی طبیعی و رنگ پوست',en:'Natural beauty enhance', anim:'a-beauty' },
      { cmd:'/rimlight',       fa:'نور حاشیه‌ای دور سوژه',        en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/backgroundblur', fa:'محو شدن پس‌زمینه، برجستگی سوژه',en:'Blurred background, subject pop', anim:'a-backgroundblur' },
      { cmd:'/sharpfocus',     fa:'سوژه واضح و کاملاً شفاف',      en:'Razor-sharp subject', anim:'a-sharpfocus' },
      { cmd:'/monotone',       fa:'پرتره سیاه‌وسفید تک‌رنگ',      en:'Monotone B&W portrait', anim:'a-monotone' },
      { cmd:'/lowkey',         fa:'نورپردازی تیره و کم‌نور',      en:'Low-key dark lighting', anim:'a-lowkey' },
      { cmd:'/highkey',        fa:'نورپردازی روشن و پرنور',      en:'High-key bright lighting', anim:'a-highkey' },
      { cmd:'/closeup',        fa:'نمای نزدیک و پرجزئیات',       en:'Close-up portrait', anim:'a-closeup' },
      { cmd:'/fullbody',       fa:'نمایش تمام‌قد سوژه',           en:'Full-body shot', anim:'a-fullbody' },
      { cmd:'/candid',         fa:'لحظه طبیعی و بدون ژست',       en:'Candid natural moment', anim:'a-candid' },
    ]},
];

/* ---- 2) Anatomy sections ----------------------------------- */
/* chips: { en=prompt text, fa=Persian meaning, desc=friendly "what is it?",
            art=CSS visual class }                                    */
const ANATOMY = [
  { id:'subject', icon:'🎯', fa:'موضوع', en:'Subject',
    question:{ fa:'تصویرت قراره نشون بده چی رو؟', en:'What should the image show?' },
    hint:{ fa:'اصلی‌ترین چیز تصویر — همون اول نوشته میشه', en:'The main subject — written first' },
    placeholders:['a Persian warrior riding a horse','a futuristic city at night','a woman in a red dress'],
    chips:[
      {en:'a lone traveler', fa:'یک مسافر تنها', desc:'یه آدمِ تنها تو یه راهِ طولانی، حسِ آزادی و ماجراجویی', art:'art-traveler'},
      {en:'a majestic lion', fa:'شیری باشکوه', desc:'یه شیرِ غول و باوقار، نمادِ قدرت و شجاعت', art:'art-lion'},
      {en:'a futuristic city', fa:'شهر آینده‌نگرانه', desc:'آسمان‌خراش‌های نئونی، ماشین‌های پرنده و بارون', art:'art-city'},
      {en:'a cozy coffee shop', fa:'یک کافه دنج', desc:'یه کافهِ گرم با نورِ زرد و بخارِ قهوه', art:'art-cafe'},
      {en:'a dragon over mountains', fa:'اژدهایی بالای کوه‌ها', desc:'اژدهایی بزرگِ بال‌گشوده بالای کوه‌های برفی', art:'art-dragon'},
      {en:'a child with a kite', fa:'کودکی با بادبادک', desc:'بچه‌ای که تو دشت بادبادک می‌کنه، حسِ خوشبختی', art:'art-kite'},
    ]},
  { id:'medium', icon:'🖌️', fa:'رسانه', en:'Medium',
    question:{ fa:'با چه سبک و ابزاری کشیده بشه؟', en:'Drawn with what medium?' },
    hint:{ fa:'نقاشی، عکس، رندر ۳بعدی یا...؟', en:'Painting, photo, 3D or...?' },
    placeholders:['oil painting','photograph','3D render'],
    chips:[
      {en:'oil painting', fa:'نقاشی روغن', desc:'رنگِ روغنیِ ضخیم و قلم‌موه‌ی قوی، حسِ کلاسیک و گرم', art:'art-oil'},
      {en:'photograph', fa:'عکس واقعی', desc:'مثل یه عکسِ واقعی با لنز، واقعی و شفاف', art:'art-photo'},
      {en:'3D render', fa:'رندر سه‌بعدی', desc:'مثل گرافیکِ بازی‌های جدید، صاف و براق', art:'art-3d'},
      {en:'watercolor', fa:'آبرنگ', desc:'رنگِ رقیق که تو هم پخش میشه، نازک و لطیف', art:'art-water'},
      {en:'digital art', fa:'نقاشی دیجیتال', desc:'رسمِ تمیز و مدرن با تبلت، رنگ‌های کامل', art:'art-digital'},
      {en:'pencil sketch', fa:'طرح مدادی', desc:'خطوطِ مدادیِ سریع، خام و صمیمی', art:'art-pencil'},
      {en:'concept art', fa:'کانسپت آرت', desc:'طرحِ اولیه برای فیلم و بازی، دراماتیک و فضایی', art:'art-concept'},
      {en:'anime style', fa:'سبک انیمه', desc:'چشم‌های بزرگ، خطوطِ تمیز و رنگ‌های شاد', art:'art-anime'},
      {en:'pixel art', fa:'پیکسل آرت', desc:'مثل بازی‌های قدیمیِ ۸بیتی، مربع‌مربع', art:'art-pixel'},
      {en:'clay model', fa:'مجل سفالی', desc:'مثل یه مجسمهِ گلِ خشک، مات و دست‌ساز', art:'art-clay'},
    ]},
  { id:'style', icon:'🎭', fa:'سبک', en:'Style',
    question:{ fa:'حال‌وهوای تصویر چی باشه؟', en:'What mood and style?' },
    hint:{ fa:'فضای کلی کار: حماسی، تاریک، بازیگوش...', en:'Overall mood: epic, dark, playful...' },
    placeholders:['epic fantasy','cyberpunk','minimalist'],
    chips:[
      {en:'epic fantasy', fa:'فانتزی حماسی', desc:'دنیایِ جنگجویان و جادو، نوری در تاریکی', art:'art-fantasy'},
      {en:'cyberpunk', fa:'سایبرپانک', desc:'آینده‌ی تاریک با نورِ نئونِ صورتی و آبی', art:'art-cyber'},
      {en:'minimalist', fa:'مینیمال', desc:'یه سوژه روی پس‌زمینهِ خالی، ساده و شیک', art:'art-minimal'},
      {en:'steampunk', fa:'استیم‌پانک', desc:'ماشین‌های بخار و چرخ‌دنده‌های مسی، قرنِ ۱۹', art:'art-steam'},
      {en:'surrealism', fa:'سوررئال', desc:'مثل خواب: چیزهای غیرممکن کنار هم', art:'art-surreal'},
      {en:'art deco', fa:'آرت دکو', desc:'خطوطِ هندسی و طلاییِ دهه‌ی ۱۹۲۰، مجلل', art:'art-deco'},
      {en:'vaporwave', fa:'ویپورویو', desc:'غروبِ صورتی، شبکه‌های نئونی و نوستالژی', art:'art-vapor'},
      {en:'gothic', fa:'گوتیک', desc:'قلعه‌های تاریک، سایه‌های عمیق و رمز و راز', art:'art-gothic'},
      {en:'studio ghibli style', fa:'سبک استودیو جیبلی', desc:'طبیعتِ نرم و ابرهای پف‌دار، گرمِ داستانی', art:'art-ghibli'},
      {en:'photorealistic', fa:'فتورئالیست', desc:'انقدر واقعی که نفهمی عکسه یا نقاشی', art:'art-real'},
    ]},
  { id:'artist', icon:'👨‍🎨', fa:'هنرمند', en:'Artist',
    question:{ fa:'به سبک کدوم هنرمند باشه؟', en:'In which artist\'s style?' },
    hint:{ fa:'الان میشه گفت اختیاریه', en:'Optional — you can skip' },
    placeholders:['by Greg Rutkowski','in the style of Van Gogh'],
    chips:[
      {en:'by Greg Rutkowski', fa:'به سبک گرگ روتکوفسکی', desc:'نقاشِ فانتزیِ معروف: نورهای دراماتیک و قلعه‌ها', art:'art-rutkowski'},
      {en:'in the style of Van Gogh', fa:'به سبک ون‌گوگ', desc:'قلم‌موه‌های چرخان و آسمانِ موج‌دار، مثل شب پرستاره', art:'art-vangogh'},
      {en:'by Alphonse Mucha', fa:'به سبک آلفونس موشا', desc:'خطوطِ منحنی و تزئیناتِ گل، هنرِ نو', art:'art-mucha'},
      {en:'by Beeple', fa:'به سبک بیپل', desc:'هنرِ دیجیتالِ عجیب و روزمره، کنتراستِ بالا', art:'art-beeple'},
      {en:'by H.R. Giger', fa:'به سبک اچ‌آر گیگر', desc:'دنیای بیومکانیکِ تاریک، مثل فیلمِ بیگانه', art:'art-giger'},
      {en:'by Hayao Miyazaki', fa:'به سبک هایائو میازاکی', desc:'هیجان و طبیعتِ جیبلی، قهرمان‌های جوان', art:'art-miyazaki'},
      {en:'by Frank Frazetta', fa:'به سبک فرانک فرازتا', desc:'قهرمانانِ عضلانی و هیولاها، رنگِ روغنیِ پلپ', art:'art-frazetta'},
      {en:'by Moebius', fa:'به سبک موبیوس', desc:'خطوطِ نازک و رنگ‌های بیابانیِ فرانسوی', art:'art-moebius'},
    ]},
  { id:'website', icon:'🌐', fa:'سایت', en:'Website',
    question:{ fa:'از کدوم سایتِ الهام‌بخش باشه؟', en:'Inspired by which site?' },
    hint:{ fa:'کلمه‌ای که کیفیت رو می‌ره بالا', en:'A keyword that boosts quality' },
    placeholders:['ArtStation trending','deviantart'],
    chips:[
      {en:'ArtStation trending', fa:'ترند آرت‌استیشن', desc:'محبوب‌ترین آثارِ روزِ هنرمندانِ حرفه‌ای', art:'art-artstation'},
      {en:'trending on ArtStation', fa:'پرطرفدارِ آرت‌استیشن', desc:'سبکِ در حالِ ترندِ کانسپت‌آرت', art:'art-artstation'},
      {en:'deviantart masterpiece', fa:'شاهکارِ دیویانت‌آرت', desc:'آثارِ انتخاب‌شده‌ی قدیمی‌ترین جامعه‌ی هنری', art:'art-deviant'},
      {en:'Pixiv top rated', fa:'برترین‌های پیکسیو', desc:'بهترین‌های سایتِ ژاپنی، انیمه و فانتزی', art:'art-pixiv'},
      {en:'Behance featured', fa:'منتخبِ بیهانس', desc:'پروژه‌های منتخبِ طراحیِ گرافیک', art:'art-behance'},
      {en:'CGSociety', fa:'انجمن CGSociety', desc:'بهترین‌های گرافیکِ کامپیوتریِ حرفه‌ای', art:'art-cgsociety'},
    ]},
  { id:'resolution', icon:'🖼️', fa:'کیفیت', en:'Resolution',
    question:{ fa:'کیفیت و جزئیات چقدر باشه؟', en:'How detailed?' },
    hint:{ fa:'هرچی بالاتر، پرجزئیات‌تر', en:'Higher = more detail' },
    placeholders:['8K','highly detailed'],
    chips:[
      {en:'8K', fa:'کیفیت ۸K', desc:'بالاترین کیفیتِ فعلی، مثل سینما', art:'art-8k'},
      {en:'4K', fa:'کیفیت ۴K', desc:'کیفیتِ تلویزیون‌های مدرن', art:'art-4k'},
      {en:'ultra HD', fa:'فول‌اچ‌دی', desc:'بسیار واضح و تمیز', art:'art-uhd'},
      {en:'highly detailed', fa:'بسیار پرجزئیات', desc:'جزئیاتِ زیاد توی پارچه و مو', art:'art-detailed'},
      {en:'sharp focus', fa:'فوکوس تیز', desc:'لبه‌های کاملا واضح، بدون تاری', art:'art-sharp'},
      {en:'masterpiece', fa:'شاهکار', desc:'بهترین نتیجه‌ای که مدل میتونه بده', art:'art-master'},
      {en:'best quality', fa:'بهترین کیفیت', desc:'کیفیتِ حداکثری', art:'art-bestq'},
      {en:'hyper-detailed', fa:'فوق‌جزئیات', desc:'بیشترین جزئیات ممکن، ریز تا ریز', art:'art-hyper'},
      {en:'unreal engine 5 render', fa:'رندر آنریل انجین ۵', desc:'موتورِ بازی‌سازیِ جدید، نورپردازیِ واقعی', art:'art-unreal'},
      {en:'octane render', fa:'رندر اکتین', desc:'رندرِ براق و واقعیِ صنعتی', art:'art-octane'},
    ]},
  { id:'details', icon:'🔎', fa:'جزئیات', en:'Details',
    question:{ fa:'چه جزئیاتی توی تصویر باشه؟', en:'Which details?' },
    hint:{ fa:'لباس، هوا، اشیاء، حالت و...', en:'Clothes, weather, objects, pose...' },
    placeholders:['glowing armor, flowing cape','rain on the streets'],
    chips:[
      {en:'glowing armor and flowing cape', fa:'زره درخشان و شنلِ بال‌کشنده', desc:'زرهی که نور می‌ده و شنلی تو باد', art:'art-armor'},
      {en:'rain-soaked streets', fa:'خیابان‌های خیس باران', desc:'خیابانِ خیس با انعکاسِ نور', art:'art-rain'},
      {en:'flying petals', fa:'گلبرگ‌های در حال پرواز', desc:'گلبرگ‌هایی که تو هوا شناورن', art:'art-petals'},
      {en:'swirling dust particles', fa:'ذرات غبار چرخان', desc:'ذراتِ غبار تو نورِ خورشید', art:'art-dust'},
      {en:'intricate jewelry', fa:'جواهرات ظریف', desc:'زینتِ ظریف و پرکار، مثل سلطنتی', art:'art-jewel'},
      {en:'dramatic pose', fa:'ژست دراماتیک', desc:'حالتِ نمایشی و قویِ بدن', art:'art-pose'},
      {en:'wind-blown hair', fa:'موی وزیده با باد', desc:'مویی که تو باد تکون می‌خوره', art:'art-hair'},
      {en:'neon signs reflection', fa:'انعکاس نور نئون', desc:'بازتابِ نورِ نئون روی سطحِ خیس', art:'art-neonref'},
    ]},
  { id:'color', icon:'🌈', fa:'رنگ', en:'Color',
    question:{ fa:'پالت رنگی چی باشه؟', en:'Which color palette?' },
    hint:{ fa:'رنگ‌های غالب تصویر', en:'The dominant colors' },
    placeholders:['gold and crimson','muted colors'],
    chips:[
      {en:'gold and crimson', fa:'طلایی و قرمز', desc:'رنگِ سلطنتی و گرم، شکوه', art:'art-goldred'},
      {en:'vibrant colors', fa:'رنگ‌های زنده', desc:'رنگ‌های اشباع و پرانرژی', art:'art-vibrant'},
      {en:'muted colors', fa:'رنگ‌های محو', desc:'رنگ‌های آرام و کم‌رنگ', art:'art-muted'},
      {en:'pastel palette', fa:'پالت پاستلی', desc:'رنگ‌های ملایم و پاستلی، کودکانه', art:'art-pastel'},
      {en:'monochrome', fa:'تک‌رنگ', desc:'یه رنگِ واحد، هنری و مینیمال', art:'art-mono'},
      {en:'neon blue and pink', fa:'نئونی آبی و صورتی', desc:'ترکیبِ سایبرپانکِ کلاسیک', art:'art-neonmix'},
      {en:'earthy tones', fa:'تن‌های خاکی', desc:'رنگ‌های طبیعیِ زمین', art:'art-earth'},
      {en:'black and gold', fa:'مشکی و طلایی', desc:'لوکس و مرموز، مثل شب', art:'art-blackgold'},
    ]},
  { id:'lighting', icon:'💡', fa:'نورپردازی', en:'Lighting',
    question:{ fa:'نورپردازی چطور باشه؟', en:'What kind of lighting?' },
    hint:{ fa:'نوع و جهت نور — روحِ تصویر', en:'Light type and direction' },
    placeholders:['cinematic lighting','golden hour'],
    chips:[
      {en:'cinematic lighting', fa:'نورپردازی سینمایی', desc:'نورِ داستانیِ فیلم‌ها، تضادِ زیبا', art:'a-cinematic'},
      {en:'golden hour', fa:'ساعت طلایی', desc:'نورِ گرمِ غروب و طلوع', art:'a-goldenhour'},
      {en:'studio lighting', fa:'نور استودیویی', desc:'نورِ تمیز و حرفه‌ایِ عکاسی', art:'a-softlight'},
      {en:'soft diffused light', fa:'نور نرم و پخش', desc:'نوری که از همه‌جا میاد، بدون سایه‌ی تیز', art:'a-softlight'},
      {en:'dramatic shadows', fa:'سایه‌های دراماتیک', desc:'تاریکیِ عمیق و نورِ کم، درام', art:'a-moody'},
      {en:'volumetric lighting', fa:'نورپردازی حجمی', desc:'پرتوهای نورِ قابلِ دیدن تو هوا', art:'a-volumetric'},
      {en:'backlit', fa:'نور از پشت', desc:'نور از پشتِ سوژه، هاله‌ی درخشان', art:'a-backlight'},
      {en:'neon glow', fa:'درخشش نئونی', desc:'نورِ نئونی که سوژه رو می‌بوسه', art:'a-neonlight'},
      {en:'natural sunlight', fa:'نور طبیعی خورشید', desc:'نورِ روزِ واقعی و گرم', art:'a-goldenhour'},
    ]},
];

/* ---- 3) Default negative prompt ---------------------------- */
const NEGATIVE_DEFAULTS = [
  'blurry','low quality','deformed','extra fingers','bad anatomy',
  'watermark','text','ugly','duplicate','mutated hands',
  'disfigured','bad proportions','lowres','jpeg artifacts','oversaturated'
];

/* ---- 4) UI translations ------------------------------------ */
const I18N = {
  fa:{
    dir:'rtl', lang:'فارسی',
    title:'پرامپت‌فورج', sub:'آهنگریِ پرامپت حرفه‌ای برای هوش مصنوعی',
    step:'مرحله', of:'از', next:'بعدی ←', back:'→ قبلی', skip:'رد شدن', finish:'🎯 ساختن پرامپت',
    modeImg:'🖼 تصویر', modeVid:'🎬 ویدیو', modeFast:'⚡ ترکیبی',
    modeQ:'می‌خوای پرامپت رو برای چی بسازی؟',
    shotQ:'دستورات دوربین و افکت — هرچی خواستی انتخاب کن',
    shotHint:'برای ویدیو/ترکیبی. می‌تونی چندتا رو با هم انتخاب کنی',
    paramsQ:'تنظیمات فنی (اختیاری)',
    finalTitle:'✅ پرامپتِ آماده‌ست!',
    summaryTitle:'📖 این پرامپت چی میگه؟',
    negativeTitle:'پرامپت منفی — چیزهایی که نمی‌خوام',
    copy:'📋 کپی پرامپت', copied:'✅ کپی شد!', copySummary:'📋 کپی خلاصه',
    copyBoth:'📋 کپی هر دو', copyPromptOnly:'✅ فقط پرامپت', copyNegOnly:'🚫 فقط منفی',
    save:'💾 ذخیره', restart:'🔄 از نو', surprise:'🎲 سورپرایزم کن!',
    history:'تاریخچه', historyEmpty:'هنوز چیزی ذخیره نشده.',
    weight:'وزن', boost:'＋', reduce:'－',
    steps:'Steps', cfg:'CFG', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'کپی', delHistory:'حذف', emptyHistory:'خالی‌کردن همه',
    footer:'ساخته‌شده با ❤ برای پرامپت‌نویسان',
    switchLang:'🇬🇧 English',
    customPh:'یا خودت بنویس...',
    selected:'انتخاب‌شده‌ها',
    trTitle:'🌐 بررسی ترجمه',
    trHint:'هرچی فارسی نوشتی، به انگلیسی تبدیل میشه',
    trEmpty:'متن فارسی‌ای ننوشتی. همه‌ی چیپ‌ها از قبل انگلیسی‌ان!',
    trWait:'در حال ترجمه…',
  },
  en:{
    dir:'ltr', lang:'English',
    title:'Prompt-Forge', sub:'Professional prompt blacksmithing for AI',
    step:'Step', of:'of', next:'Next →', back:'← Back', skip:'Skip', finish:'🎯 Build prompt',
    modeImg:'🖼 Image', modeVid:'🎬 Video', modeFast:'⚡ Hybrid',
    modeQ:'What are you building a prompt for?',
    shotQ:'Camera & effect commands — pick what you want',
    shotHint:'For video/hybrid. You can pick several.',
    paramsQ:'Technical settings (optional)',
    finalTitle:'✅ Your prompt is ready!',
    summaryTitle:'📖 What does it mean?',
    negativeTitle:'Negative prompt — what you DON\'T want',
    copy:'📋 Copy prompt', copied:'✅ Copied!', copySummary:'📋 Copy summary',
    copyBoth:'📋 Copy both', copyPromptOnly:'✅ Prompt only', copyNegOnly:'🚫 Negative only',
    save:'💾 Save', restart:'🔄 Restart', surprise:'🎲 Surprise me!',
    history:'History', historyEmpty:'Nothing saved yet.',
    weight:'weight', boost:'＋', reduce:'－',
    steps:'Steps', cfg:'CFG', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'Copy', delHistory:'Delete', emptyHistory:'Clear all',
    footer:'Made with ❤ for prompt engineers',
    switchLang:'🇮🇷 فارسی',
    customPh:'or type your own...',
    selected:'Selected',
    trTitle:'🌐 Translation check',
    trHint:'Your Persian text becomes English here',
    trEmpty:'No Persian text — everything is already English!',
    trWait:'translating…',
  }
};

const SAMPLERS = ['DPM++ 2M Karras','Euler a','DDIM','DPM++ SDE','UniPC','Heun'];
const ASPECTS  = ['1:1','16:9','9:16','4:3','3:2','21:9'];

/* ---- 6) Ready-made prompt presets -------------------------- */
/* picks anatomy chips by matching `en` values + optional cmds */
const PRESETS = [
  { id:'epic',   icon:'⚔️', fa:'حماسیِ فانتزی', en:'Epic Fantasy',
    fa_desc:'یه صحنه‌ی فانتزیِ دراماتیک با نورهای طلایی', mode:'img',
    chips:['a dragon over mountains','oil painting','epic fantasy','by Greg Rutkowski',
           'ArtStation trending','8K','glowing armor and flowing cape','gold and crimson','cinematic lighting'] },
  { id:'cyber',  icon:'🌃', fa:'شبِ سایبرپانک', en:'Cyberpunk Night',
    fa_desc:'شهرِ آینده با نورهای نئونِ صورتی و آبی', mode:'vid',
    chips:['a futuristic city','digital art','cyberpunk','neon signs reflection',
           'neon blue and pink','neon glow'],
    cmds:['/neonlight','/rain','/tracking'] },
  { id:'ghibli', icon:'🌿', fa:'طبیعتِ جیبلی', en:'Ghibli Nature',
    fa_desc:'فضای سبک استودیو جیبلی، گرم و داستانی', mode:'img',
    chips:['a child with a kite','watercolor','studio ghibli style','by Hayao Miyazaki',
           'flying petals','pastel palette','natural sunlight'] },
  { id:'portrait',icon:'🧑‍🎤', fa:'پرتره‌ی استودیویی', en:'Studio Portrait',
    fa_desc:'پرتره‌ی حرفه‌ای با نورِ نرم و بوکه', mode:'img',
    chips:['photograph','photorealistic','by Beeple','8K','sharp focus','soft diffused light',
           'background blur','studio lighting'] },
  { id:'surreal',icon:'🌀', fa:'خوابِ سوررئال', en:'Surreal Dream',
    fa_desc:'دنیایِ غیرممکنِ خواب‌گونه با رنگ‌های عجیب', mode:'fast',
    chips:['a lone traveler','watercolor','surrealism','by Moebius','flying petals',
           'pastel palette','volumetric lighting'] },
  { id:'noir',   icon:'🖤', fa:'فیلمِ نوآر', en:'Film Noir',
    fa_desc:'سیاه‌وسفیدِ دراماتیک با سایه‌های عمیق', mode:'vid',
    chips:['a lone traveler','photograph','gothic','by Frank Frazetta','dramatic pose',
           'monochrome','dramatic shadows','low-key'],
    cmds:['/lowangle','/slowmotion','/freeze'] },
];

/* ---- 5) Persian -> English prompt dictionary (offline) ---- */
const FA_EN = {
  /* subjects & nouns */
  'شیر':'lion','اژدها':'dragon','گربه':'cat','سگ':'dog','اسب':'horse','جنگجو':'warrior',
  'زن':'woman','مرد':'man','کودک':'child','دختر':'girl','پسر':'boy','شهر':'city',
  'کوه':'mountain','دریا':'sea','جنگل':'forest','صحرا':'desert','قلعه':'castle','روستا':'village',
  'ماهی':'fish','پرنده':'bird','گل':'flower','درخت':'tree','ماشین':'car','هواپیما':'airplane',
  'قطار':'train','کشتی':'ship','قایق':'boat','خانه':'house','باغ':'garden','رودخانه':'river',
  'آبشار':'waterfall','ساحل':'beach','جزیره':'island','آسمان':'sky','ابر':'cloud','خورشید':'sun',
  'ماه':'moon','ستاره':'star','باران':'rain','برف':'snow','باد':'wind','آتش':'fire','دود':'smoke',
  'جادوگر':'wizard','جادو':'magic','شاه':'king','ملکه':'queen','شاهزاده':'prince','فرشته':'angel',
  'غول':'giant','قهرمان':'hero','شمشیر':'sword','سپر':'shield','زره':'armor','تاج':'crown',
  'عصا':'staff','کمان':'bow','پیکان':'arrow','کلاه':'helmet','ردا':'cloak','شنل':'cape',
  'ربات':'robot','سامورایی':'samurai','نینجا':'ninja','فضانورد':'astronaut','هواپیما':'airplane',
  'تراکتور':'tractor','موتور':'motorcycle','دوچرخه':'bicycle','کامیون':'truck','اتوبوس':'bus',
  'معبد':'temple','کلیسا':'church','مسجد':'mosque','برج':'tower','دیوار':'wall','پل':'bridge',
  'خیابان':'street','جاده':'road','بازار':'market','کافه':'cafe','رستوران':'restaurant',
  'کتاب':'book','نگارخانه':'gallery','آینه':'mirror','ساعت':'clock','گوی':'orb','چراغ':'lamp',
  /* attributes */
  'زیبا':'beautiful','بسیار':'very','خیلی':'very','بزرگ':'big','کوچک':'small','تاریک':'dark',
  'روشن':'bright','سریع':'fast','کند':'slow','قدرتمند':'powerful','قوی':'strong','جوان':'young',
  'پیر':'old','بلند':'tall','کوتاه':'short','پهن':'wide','باریک':'narrow','وسیع':'vast',
  'عظیم':'massive','شگفت‌انگیز':'amazing','معمایی':'mysterious','ترسناک':'scary','خشن':'fierce',
  'ملایم':'gentle','آرام':'calm','خشمگین':'angry','خوشحال':'happy','غمگین':'sad','تنها':'lonely',
  'شجاع':'brave','باوفا':'loyal','دوست‌داشتنی':'lovely','باشکوه':'majestic','سلطنتی':'royal',
  /* colors */
  'سفید':'white','مشکی':'black','قرمز':'red','آبی':'blue','سبز':'green','زرد':'yellow',
  'نارنجی':'orange','بنفش':'purple','صورتی':'pink','طلایی':'golden','نقره‌ای':'silver',
  'خاکی':'earthy','فیروزه‌ای':'turquoise','ارغوانی':'magenta','کرم':'cream','طوسی':'gray',
  'سرخابی':'fuchsia','یشمی':'jade','مرجانی':'coral','عنابی':'maroon','نفتی':'navy',
  /* styles & mediums */
  'نقاشی':'painting','عکس':'photo','آبرنگ':'watercolor','روغن':'oil','دیجیتال':'digital',
  'انیمه':'anime','فانتزی':'fantasy','سایبرپانک':'cyberpunk','واقعی':'realistic','طبیعت':'nature',
  'عاشقانه':'romantic','کلاسیک':'classic','مدرن':'modern','مینیمال':'minimal','گوتیک':'gothic',
  'استیم':'steampunk','بازیگوش':'playful','حماسی':'epic','افسانه‌ای':'legendary','روایی':'mythical',
  'تخیلی':'fiction','علمی':'science','فضایی':'space','زرشکی':'crimson','سپیدی':'pure',
  /* lighting & atmosphere */
  'نور':'light','سایه':'shadow','درخشش':'glow','روشنایی':'brightness','تاریکی':'darkness',
  'مه':'fog','بارانی':'rainy','آفتابی':'sunny','ابری':'cloudy','طوفانی':'stormy','مه‌آلود':'misty',
  /* quality */
  'کیفیت':'quality','جزئیات':'details','وضوح':'clarity','دقیق':'detailed','شارپ':'sharp',
  /* actions */
  'دویدن':'running','راه رفتن':'walking','پرواز':'flying','نشسته':'sitting','ایستاده':'standing',
  'لبخند':'smile','گریه':'crying','نگاه':'looking','خوابیده':'sleeping','جنگیدن':'fighting',
  /* common words */
  'یک':'a','با':'with','در':'in','روی':'on','زیر':'under','کنار':'near','بالای':'above',
  'و':'and','داخل':'inside','خارج':'outside','وسط':'middle','انتها':'end','ابتدا':'start',
  'داشته':'holding','برداشته':'carrying','پوشیده':'wearing','نشون':'showing',
  /* compound helpers */
  'نقاشی روغن':'oil painting','عکس واقعی':'realistic photo','کیفیت بالا':'high quality',
  'خیلی بزرگ':'huge','خیلی کوچک':'tiny','دختر جوان':'young girl','پسر جوان':'young boy',
  'نگاه کردن':'looking at','در حال':'in the middle of',
};
