/* ============================================================
   PROMPT-FORGE  |  Data layer
   99 video/shot commands (9 groups) + 9 anatomy sections
   ============================================================ */

/* ---- 1) Shot / video command groups ------------------------ */
/* anim: CSS class used for the mini live-preview              */
const COMMANDS = [
  { id:'g1', icon:'🎬', fa:'دستورهای دوربین و حرکت', en:'Camera & Movement',
    items:[
      { cmd:'/cinematic',   fa:'شات ویدیویی سینمایی و حرفه‌ای',   en:'Cinematic professional shot', anim:'a-cinematic' },
      { cmd:'/droneview',   fa:'نمای هوایی از بالا مثل پهپاد',    en:'Aerial drone view from above', anim:'a-droneview' },
      { cmd:'/closeup',     fa:'نمای نزدیک و پرجزئیات',           en:'Close-up with high detail', anim:'a-closeup' },
      { cmd:'/wideangle',   fa:'نمای باز و گسترده با عمق بیشتر',  en:'Wide-angle expansive view', anim:'a-wideangle' },
      { cmd:'/orbit',       fa:'چرخش روان دور سوژه',              en:'Smooth orbit around subject', anim:'a-orbit' },
      { cmd:'/dollyin',     fa:'نزدیک شدن دوربین به سوژه',        en:'Dolly in toward subject', anim:'a-dollyin' },
      { cmd:'/dollyout',    fa:'عقب رفتن دوربین از سوژه',         en:'Dolly out from subject', anim:'a-dollyout' },
      { cmd:'/tracking',    fa:'دنبال کردن سوژه حین حرکت',        en:'Tracking moving subject', anim:'a-tracking' },
      { cmd:'/slowmotion',  fa:'صحنه آهسته با جزئیات بیشتر',      en:'Slow motion detail shot', anim:'a-slowmotion' },
      { cmd:'/timelapse',   fa:'تایم‌لپس با گذر سریع زمان',        en:'Timelapse, fast time passage', anim:'a-timelapse' },
      { cmd:'/hyperlapse',  fa:'حرکت سریع دوربین، دینامیک بالا',  en:'Hyperlapse fast dynamic move', anim:'a-hyperlapse' },
    ]},
  { id:'g2', icon:'📐', fa:'زاویه‌های حرفه‌ای دوربین', en:'Pro Camera Angles',
    items:[
      { cmd:'/lowangle',       fa:'نمای از پایین برای حس قدرت',   en:'Low angle, powerful feel', anim:'a-lowangle' },
      { cmd:'/highangle',      fa:'نمای از بالا برای دید گسترده', en:'High angle wide view', anim:'a-highangle' },
      { cmd:'/overhead',       fa:'نمای کاملاً عمودی از بالا',     en:'Overhead top-down view', anim:'a-overhead' },
      { cmd:'/pov',            fa:'نمای اول‌شخص از چشم سوژه',     en:'POV first-person view', anim:'a-pov' },
      { cmd:'/overtheshoulder',fa:'نمای از پشت شانه + محیط',      en:'Over the shoulder shot', anim:'a-OTS' },
      { cmd:'/establishing',   fa:'نمای معرفی صحنه و مکان',       en:'Establishing shot', anim:'a-establishing' },
      { cmd:'/rackfocus',      fa:'تغییر فوکوس نرم بین سوژه‌ها',  en:'Rack focus between subjects', anim:'a-rackfocus' },
      { cmd:'/handheld',       fa:'حرکت دوربین دستی و طبیعی',     en:'Handheld natural motion', anim:'a-handheld' },
      { cmd:'/steadicam',      fa:'حرکت نرم و پایدار دوربین',     en:'Steadicam smooth shot', anim:'a-steadicam' },
      { cmd:'/craneup',        fa:'حرکت رو به بالا سینمایی',      en:'Crane up cinematic move', anim:'a-craneup' },
      { cmd:'/cranedown',      fa:'حرکت رو به پایین، نمای گسترده',en:'Crane down wide reveal', anim:'a-cranedown' },
    ]},
  { id:'g3', icon:'🏃', fa:'دستورهای حرکت و اکشن', en:'Motion & Action',
    items:[
      { cmd:'/running',    fa:'دویدن با حس سرعت و انرژی',     en:'Running with speed energy', anim:'a-running' },
      { cmd:'/walking',    fa:'راه رفتن طبیعی و واقعی',       en:'Natural walking', anim:'a-walking' },
      { cmd:'/turnaround', fa:'چرخش روان ۳۶۰ درجه دور سوژه', en:'360 turnaround around subject', anim:'a-turnaround' },
      { cmd:'/reveal',     fa:'نمایش تدریجی سوژه یا صحنه',   en:'Gradual reveal', anim:'a-reveal' },
      { cmd:'/entrance',   fa:'ورود سینمایی شخصیت به صحنه',  en:'Cinematic character entrance', anim:'a-entrance' },
      { cmd:'/exit',       fa:'خروج سینمایی از صحنه',         en:'Cinematic exit', anim:'a-exit' },
      { cmd:'/freeze',     fa:'فریز کردن حرکت در لحظه خاص',  en:'Freeze frame moment', anim:'a-freeze' },
      { cmd:'/speedramp',  fa:'ترکیب حرکت آهسته و سریع',     en:'Slow-to-fast speed ramp', anim:'a-speedramp' },
      { cmd:'/bullettime', fa:'افکت آهسته سبک Bullet Time',  en:'Bullet Time slow effect', anim:'a-bullettime' },
      { cmd:'/floating',   fa:'حس شناور بودن در فضا',        en:'Floating in space', anim:'a-floating' },
      { cmd:'/falling',    fa:'صحنه سقوط دراماتیک',          en:'Dramatic falling', anim:'a-falling' },
    ]},
  { id:'g4', icon:'💡', fa:'نورپردازی سینمایی', en:'Cinematic Lighting',
    items:[
      { cmd:'/goldenhour', fa:'نور گرم ساعت طلایی',        en:'Golden hour warm light', anim:'a-goldenhour' },
      { cmd:'/bluehour',   fa:'نور سرد و آرام گرگ‌ومیش',    en:'Blue hour twilight', anim:'a-bluehour' },
      { cmd:'/neonlight',  fa:'نور نئونی سینمایی و زنده',  en:'Vivid neon lighting', anim:'a-neonlight' },
      { cmd:'/moody',      fa:'نور تیره و دراماتیک',       en:'Moody dramatic lighting', anim:'a-moody' },
      { cmd:'/softlight',  fa:'نور نرم و پخش‌شده استودیو', en:'Soft diffused studio light', anim:'a-softlight' },
      { cmd:'/rimlight',   fa:'نور حاشیه‌ای دور سوژه',     en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/silhouette', fa:'نمای قدرتمند سیلوئت',       en:'Strong silhouette', anim:'a-silhouette' },
      { cmd:'/spotlight',  fa:'نور متمرکز روی سوژه',       en:'Focused spotlight', anim:'a-spotlight' },
      { cmd:'/volumetric', fa:'پرتوهای حجمی اتمسفریک',     en:'Volumetric light beams', anim:'a-volumetric' },
      { cmd:'/backlight',  fa:'نور قوی از پشت سوژه',       en:'Strong backlight', anim:'a-backlight' },
      { cmd:'/nightscene', fa:'صحنه شب سینمایی و واقعی',   en:'Cinematic night scene', anim:'a-nightscene' },
    ]},
  { id:'g5', icon:'🖼️', fa:'ترکیب‌بندی و کادربندی', en:'Composition & Framing',
    items:[
      { cmd:'/wide',          fa:'کادر باز برای نمایش کامل صحنه',  en:'Wide full-scene frame', anim:'a-wide' },
      { cmd:'/tight',         fa:'کادر بسته برای تمرکز روی سوژه',  en:'Tight subject-focused frame', anim:'a-tight' },
      { cmd:'/minimal',       fa:'ترکیب‌بندی ساده و مینیمال',      en:'Minimal composition', anim:'a-minimal' },
      { cmd:'/leadinglines',  fa:'خطوط هدایت‌گر نگاه',             en:'Leading lines', anim:'a-leadinglines' },
      { cmd:'/ruleofthirds',  fa:'قانون یک‌سوم، کادر متعادل',       en:'Rule of thirds balance', anim:'a-ruleofthirds' },
      { cmd:'/symmetry',      fa:'ترکیب‌بندی متقارن',              en:'Symmetrical composition', anim:'a-symmetry' },
      { cmd:'/foreground',    fa:'پیش‌زمینه قوی برای عمق بیشتر',   en:'Strong foreground depth', anim:'a-foreground' },
      { cmd:'/framewithinframe', fa:'قاب طبیعی درون صحنه',         en:'Frame within a frame', anim:'a-framewithinframe' },
      { cmd:'/diagonal',      fa:'ترکیب‌بندی مورب و پویا',         en:'Diagonal dynamic composition', anim:'a-diagonal' },
      { cmd:'/centered',      fa:'قرارگیری سوژه در مرکز',          en:'Centered subject', anim:'a-centered' },
      { cmd:'/negativespace', fa:'استفاده مؤثر از فضای منفی',      en:'Effective negative space', anim:'a-negativespace' },
    ]},
  { id:'g6', icon:'✨', fa:'افکت‌های دوربین', en:'Camera Effects',
    items:[
      { cmd:'/motionblur', fa:'محوشدگی حرکت برای حس سرعت',  en:'Motion blur for speed', anim:'a-motionblur' },
      { cmd:'/zoomblur',   fa:'محوشدگی زوم دراماتیک',       en:'Dramatic zoom blur', anim:'a-zoomblur' },
      { cmd:'/bokeh',      fa:'بوکه در پس‌زمینه',           en:'Background bokeh', anim:'a-bokeh' },
      { cmd:'/lensflare',  fa:'فلر سینمایی لنز',            en:'Cinematic lens flare', anim:'a-lensflare' },
      { cmd:'/vignette',   fa:'تیره‌کردن لبه‌های تصویر',     en:'Vignette dark edges', anim:'a-vignette' },
      { cmd:'/splittone',  fa:'درجه‌بندی رنگی دوگانه',      en:'Split-tone grading', anim:'a-splittone' },
      { cmd:'/monochrome', fa:'تبدیل صحنه به سیاه‌وسفید',   en:'Monochrome black & white', anim:'a-monochrome' },
      { cmd:'/radialblur', fa:'محوشدگی شعاعی و پویا',       en:'Radial blur', anim:'a-radialblur' },
      { cmd:'/prism',      fa:'شکست نور منشوری',            en:'Prism light refraction', anim:'a-prism' },
      { cmd:'/glitch',     fa:'افکت گلیچ دیجیتال',          en:'Digital glitch effect', anim:'a-glitch' },
      { cmd:'/filmgrain',  fa:'دانه‌های فیلم با حس قدیمی',   en:'Vintage film grain', anim:'a-filmgrain' },
    ]},
  { id:'g7', icon:'🔍', fa:'فوکوس و عمق میدان', en:'Focus & Depth of Field',
    items:[
      { cmd:'/macro',         fa:'جزئیات بسیار نزدیک',          en:'Extreme macro detail', anim:'a-macro' },
      { cmd:'/shallowdepth',  fa:'عمق میدان کم',               en:'Shallow depth of field', anim:'a-shallowdepth' },
      { cmd:'/deepfocus',     fa:'وضوح پیش و پس‌زمینه',        en:'Deep focus, all sharp', anim:'a-deepfocus' },
      { cmd:'/selectivefocus',fa:'فوکوس روی سوژه، محو شدن اطراف',en:'Selective focus', anim:'a-selectivefocus' },
      { cmd:'/eyefocus',      fa:'فوکوس دقیق روی چشم‌ها',      en:'Sharp eye focus', anim:'a-eyefocus' },
      { cmd:'/centerfocus',   fa:'وضوح مرکز، محو شدن اطراف',   en:'Center focus, soft edges', anim:'a-centerfocus' },
      { cmd:'/tunnelfocus',   fa:'فوکوس تونلی برای جلب توجه',  en:'Tunnel focus', anim:'a-tunnelfocus' },
      { cmd:'/focusstack',    fa:'ترکیب چند فوکوس برای وضوح',  en:'Focus stacking sharpness', anim:'a-focusstack' },
      { cmd:'/dropfocus',     fa:'فوکوس روی قطره یا جزء خاص',  en:'Focus on a droplet detail', anim:'a-dropfocus' },
      { cmd:'/manualfocus',   fa:'کنترل دستی فوکوس',           en:'Manual focus control', anim:'a-manualfocus' },
      { cmd:'/bokehshape',    fa:'شکل‌دهی سفارشی نورهای بوکه', en:'Custom-shaped bokeh', anim:'a-bokehshape' },
    ]},
  { id:'g8', icon:'🎨', fa:'اصلاح و درجه‌بندی رنگ', en:'Color Correction & Grading',
    items:[
      { cmd:'/warm',        fa:'تن‌های گرم برای حس صمیمی',  en:'Warm tones, cozy feel', anim:'a-warm' },
      { cmd:'/cool',        fa:'تن‌های سرد برای حس آرام',   en:'Cool tones, calm feel', anim:'a-cool' },
      { cmd:'/contrast',    fa:'افزایش کنتراست تصویر',      en:'Increased contrast', anim:'a-contrast' },
      { cmd:'/exposure',    fa:'تنظیم روشنایی و نوردهی',    en:'Exposure adjustment', anim:'a-exposure' },
      { cmd:'/saturation',  fa:'افزایش یا کاهش غلظت رنگ',   en:'Color saturation control', anim:'a-saturation' },
      { cmd:'/desaturate',  fa:'کاهش رنگ برای ظاهر خنثی',   en:'Desaturated neutral look', anim:'a-desaturate' },
      { cmd:'/cinematic',   fa:'درجه‌بندی رنگ سینمایی',     en:'Cinematic color grading', anim:'a-cinematicgrade' },
      { cmd:'/tealorange',  fa:'رنگ‌بندی فیروزه‌ای و نارنجی',en:'Teal & orange grade', anim:'a-tealorange' },
      { cmd:'/vibrant',     fa:'تقویت رنگ‌ها، تصویر زنده‌تر',en:'Vibrant boosted colors', anim:'a-vibrant' },
      { cmd:'/bw',          fa:'تبدیل به سیاه‌وسفید',       en:'Black & white', anim:'a-bw' },
      { cmd:'/neon',        fa:'درجه‌بندی رنگ نئونی',       en:'Neon color grade', anim:'a-neon' },
    ]},
  { id:'g9', icon:'🧑‍🎤', fa:'پرتره و سوژه', en:'Portrait & Subject',
    items:[
      { cmd:'/portrait',       fa:'نمای پرتره',                   en:'Portrait shot', anim:'a-portrait' },
      { cmd:'/beauty',         fa:'تقویت زیبایی طبیعی و رنگ پوست',en:'Natural beauty enhance', anim:'a-beauty' },
      { cmd:'/rimlight',       fa:'نور حاشیه‌ای دور سوژه',        en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/backgroundblur', fa:'محو شدن پس‌زمینه، برجستگی سوژه',en:'Blurred background, subject pop', anim:'a-backgroundblur' },
      { cmd:'/sharpfocus',     fa:'سوژه واضح و کاملاً شفاف',      en:'Razor-sharp subject', anim:'a-sharpfocus' },
      { cmd:'/monotone',       fa:'پرتره سیاه‌وسفید تک‌رنگ',      en:'Monotone B&W portrait', anim:'a-monotone' },
      { cmd:'/lowkey',         fa:'نورپردازی تیره و کم‌نور',      en:'Low-key dark lighting', anim:'a-lowkey' },
      { cmd:'/highkey',        fa:'نورپردازی روشن و پرنور',      en:'High-key bright lighting', anim:'a-highkey' },
      { cmd:'/closeup',        fa:'نمای نزدیک و پرجزئیات',       en:'Close-up portrait', anim:'a-closeup' },
      { cmd:'/fullbody',       fa:'نمایش تمام‌قد سوژه',           en:'Full-body shot', anim:'a-fullbody' },
      { cmd:'/candid',         fa:'لحظه طبیعی و بدون ژست',       en:'Candid natural moment', anim:'a-candid' },
    ]},
];

/* ---- 2) Anatomy sections (classic SD prompt) ---------------- */
const ANATOMY = [
  { id:'subject',   icon:'🎯', fa:'موضوع',       en:'Subject',
    hint:'اصلی‌ترین چیز تصویر — اول از همه نوشته میشه',
    placeholders:['a Persian warrior riding a horse','a futuristic city at night','a woman in a red dress'],
    chips:['a lone traveler','a majestic lion','a futuristic city','a cozy coffee shop','a dragon over mountains','a child with a kite'] },
  { id:'medium',    icon:'🖌️', fa:'رسانه',       en:'Medium',
    hint:'با چه ابزاری کشیده شده؟',
    placeholders:['oil painting','photograph','3D render'],
    chips:['oil painting','photograph','3D render','watercolor','digital art','pencil sketch','concept art','anime style','pixel art','clay model'] },
  { id:'style',     icon:'🎭', fa:'سبک',         en:'Style',
    hint:'حال‌وهوای کلی تصویر',
    placeholders:['epic fantasy','cyberpunk','minimalist'],
    chips:['epic fantasy','cyberpunk','minimalist','steampunk','surrealism','art deco','vaporwave','gothic','studio ghibli style','photorealistic'] },
  { id:'artist',    icon:'👨‍🎨', fa:'هنرمند',    en:'Artist',
    hint:'به سبک کی کشیده بشه؟',
    placeholders:['by Greg Rutkowski','in the style of Van Gogh'],
    chips:['by Greg Rutkowski','in the style of Van Gogh','by Alphonse Mucha','by Beeple','by H.R. Giger','by Hayao Miyazaki','by Frank Frazetta','by Moebius'] },
  { id:'website',   icon:'🌐', fa:'سایت',        en:'Website',
    hint:'جایی که آثار خوبی توش هست',
    placeholders:['ArtStation trending','deviantart'],
    chips:['ArtStation trending','trending on ArtStation','deviantart masterpiece','Pixiv top rated','Behance featured','CGSociety'] },
  { id:'resolution',icon:'🖼️', fa:'کیفیت',       en:'Resolution',
    hint:'وضوح و میزان جزئیات',
    placeholders:['8K','highly detailed'],
    chips:['8K','4K','ultra HD','highly detailed','sharp focus','masterpiece','best quality','hyper-detailed','unreal engine 5 render','octane render'] },
  { id:'details',   icon:'🔎', fa:'جزئیات',       en:'Details',
    hint:'توصیف دقیق صحنه — لباس، حالت، اشیاء',
    placeholders:['glowing armor, flowing cape','rain on the streets'],
    chips:['glowing armor and flowing cape','rain-soaked streets','flying petals','swirling dust particles','intricate jewelry','dramatic pose','wind-blown hair','neon signs reflection'] },
  { id:'color',     icon:'🌈', fa:'رنگ',         en:'Color',
    hint:'پالت رنگی کلی',
    placeholders:['gold and crimson','muted colors'],
    chips:['gold and crimson','vibrant colors','muted colors','pastel palette','monochrome','neon blue and pink','earthy tones','black and gold'] },
  { id:'lighting',  icon:'💡', fa:'نورپردازی',   en:'Lighting',
    hint:'نوع و جهت نور',
    placeholders:['cinematic lighting','golden hour'],
    chips:['cinematic lighting','golden hour','studio lighting','soft diffused light','dramatic shadows','volumetric lighting','backlit','neon glow','natural sunlight'] },
];

/* ---- 3) Default negative prompt ---------------------------- */
const NEGATIVE_DEFAULTS = [
  'blurry','low quality','deformed','extra fingers','bad anatomy',
  'watermark','text','ugly','duplicate','mutated hands',
  'disfigured','bad proportions','lowres','jpeg artifacts','oversaturated'
];

/* ---- 4) UI translations (FA / EN) -------------------------- */
const I18N = {
  fa:{
    dir:'rtl', lang:'فارسی',
    title:'پرامپت‌فورج', sub:'آهنگریِ پرامپت حرفه‌ای برای هوش مصنوعی',
    tabAnatomy:'آناتومی پرامپت', tabShot:'دستورات شات',
    modeImg:'🖼 تصویر', modeVid:'🎬 ویدیو', modeFast:'⚡ سریع',
    anatomyTitle:'۹ تیکه‌ی پازل پرامپت (از کلی به جزئی)',
    shotTitle:'۹۹ دستور حرفه‌ای دوربین و افکت',
    preview:'پیش‌نمایش زنده‌ی پرامپت',
    negative:'پرامپت منفی (چیزهایی که نمی‌خوام)',
    params:'پارامترها',
    copy:'📋 کپی', copied:'✅ کپی شد!', save:'💾 ذخیره', clear:'🗑 پاک‌کردن',
    surprise:'🎲 سورپرایزم کن!',
    history:'تاریخچه‌ی پرامپت‌ها', historyEmpty:'هنوز چیزی ذخیره نشده.',
    weight:'وزن', boost:'＋ تقویت', reduce:'－ تضعیف',
    steps:'Steps', cfg:'CFG Scale', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'کپی این پرامپت', delHistory:'حذف', emptyHistory:'خالی‌کردن کل تاریخچه',
    footer:'ساخته‌شده با ❤ برای پرامپت‌نویسان',
    switchLang:'🇬🇧 English',
    hintTxt:'یه چیپ رو انتخاب کن یا خودت تایپ کن — پرامپت همینجا ساخته میشه',
  },
  en:{
    dir:'ltr', lang:'English',
    title:'Prompt-Forge', sub:'Professional prompt blacksmithing for AI',
    tabAnatomy:'Prompt Anatomy', tabShot:'Shot Commands',
    modeImg:'🖼 Image', modeVid:'🎬 Video', modeFast:'⚡ Fast',
    anatomyTitle:'The 9 prompt puzzle pieces (broad → detail)',
    shotTitle:'99 pro camera & effect commands',
    preview:'Live prompt preview',
    negative:'Negative prompt (what you DON\'T want)',
    params:'Parameters',
    copy:'📋 Copy', copied:'✅ Copied!', save:'💾 Save', clear:'🗑 Clear',
    surprise:'🎲 Surprise me!',
    history:'Prompt history', historyEmpty:'Nothing saved yet.',
    weight:'weight', boost:'＋ Boost', reduce:'− Reduce',
    steps:'Steps', cfg:'CFG Scale', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'Copy this prompt', delHistory:'Delete', emptyHistory:'Clear all history',
    footer:'Made with ❤ for prompt engineers',
    switchLang:'🇮🇷 فارسی',
    hintTxt:'Pick a chip or type your own — the prompt builds right here',
  }
};

const SAMPLERS = ['DPM++ 2M Karras','Euler a','DDIM','DPM++ SDE','UniPC','Heun'];
const ASPECTS  = ['1:1','16:9','9:16','4:3','3:2','21:9'];
