/* ============================================================
   PROMPT-FORGE v2  |  Data layer
   99 video/shot commands + 9 anatomy sections (bilingual chips)
   ============================================================ */

/* ---- 1) Shot / video command groups ------------------------ */
const COMMANDS = [
  { id:'g1', icon:'🎬', fa:'دستورهای دوربین و حرکت', en:'Camera & Movement',
    items:[
      { cmd:'/cinematic',   fa:'شات ویدیویی سینمایی و حرفه‌ای',   en:'Cinematic professional shot', anim:'a-cinematic' },
      { cmd:'/droneview',   fa:'نمای هوایی از بالا مثل پهپاد',    en:'Aerial drone view from above', anim:'a-droneview' },
      { cmd:'/closeup',     fa:'نمای نزدیک و پرجزئیات',           en:'Close-up with high detail', anim:'a-closeup' },
      { cmd:'/wideangle',   fa:'نمای باز و گسترده با عمق بیشتر',  en:'Wide-angle expansive view', anim:'a-wideangle' },
      { cmd:'/orbit',       fa:'چرخش روان دور سوژه',              en:'Smooth orbit around subject', anim:'a-orbit' },
      { cmd:'/dollyin',     fa:'نزدیک شدن دوربین به سوژه',        en:'Dolly in toward subject', anim:'a-dollyin' },
      { cmd:'/dollyout',    fa:'عقب رفتن دوربین از سوژه',         en:'Dolly out from subject', anim:'a-dollyout' },
      { cmd:'/tracking',    fa:'دنبال کردن سوژه حین حرکت',        en:'Tracking moving subject', anim:'a-tracking' },
      { cmd:'/slowmotion',  fa:'صحنه آهسته با جزئیات بیشتر',      en:'Slow motion detail shot', anim:'a-slowmotion' },
      { cmd:'/timelapse',   fa:'تایم‌لپس با گذر سریع زمان',        en:'Timelapse, fast time passage', anim:'a-timelapse' },
      { cmd:'/hyperlapse',  fa:'حرکت سریع دوربین، دینامیک بالا',  en:'Hyperlapse fast dynamic move', anim:'a-hyperlapse' },
    ]},
  { id:'g2', icon:'📐', fa:'زاویه‌های حرفه‌ای دوربین', en:'Pro Camera Angles',
    items:[
      { cmd:'/lowangle',       fa:'نمای از پایین برای حس قدرت',   en:'Low angle, powerful feel', anim:'a-lowangle' },
      { cmd:'/highangle',      fa:'نمای از بالا برای دید گسترده', en:'High angle wide view', anim:'a-highangle' },
      { cmd:'/overhead',       fa:'نمای کاملاً عمودی از بالا',     en:'Overhead top-down view', anim:'a-overhead' },
      { cmd:'/pov',            fa:'نمای اول‌شخص از چشم سوژه',     en:'POV first-person view', anim:'a-pov' },
      { cmd:'/overtheshoulder',fa:'نمای از پشت شانه + محیط',      en:'Over the shoulder shot', anim:'a-OTS' },
      { cmd:'/establishing',   fa:'نمای معرفی صحنه و مکان',       en:'Establishing shot', anim:'a-establishing' },
      { cmd:'/rackfocus',      fa:'تغییر فوکوس نرم بین سوژه‌ها',  en:'Rack focus between subjects', anim:'a-rackfocus' },
      { cmd:'/handheld',       fa:'حرکت دوربین دستی و طبیعی',     en:'Handheld natural motion', anim:'a-handheld' },
      { cmd:'/steadicam',      fa:'حرکت نرم و پایدار دوربین',     en:'Steadicam smooth shot', anim:'a-steadicam' },
      { cmd:'/craneup',        fa:'حرکت رو به بالا سینمایی',      en:'Crane up cinematic move', anim:'a-craneup' },
      { cmd:'/cranedown',      fa:'حرکت رو به پایین، نمای گسترده',en:'Crane down wide reveal', anim:'a-cranedown' },
    ]},
  { id:'g3', icon:'🏃', fa:'دستورهای حرکت و اکشن', en:'Motion & Action',
    items:[
      { cmd:'/running',    fa:'دویدن با حس سرعت و انرژی',     en:'Running with speed energy', anim:'a-running' },
      { cmd:'/walking',    fa:'راه رفتن طبیعی و واقعی',       en:'Natural walking', anim:'a-walking' },
      { cmd:'/turnaround', fa:'چرخش روان ۳۶۰ درجه دور سوژه', en:'360 turnaround around subject', anim:'a-turnaround' },
      { cmd:'/reveal',     fa:'نمایش تدریجی سوژه یا صحنه',   en:'Gradual reveal', anim:'a-reveal' },
      { cmd:'/entrance',   fa:'ورود سینمایی شخصیت به صحنه',  en:'Cinematic character entrance', anim:'a-entrance' },
      { cmd:'/exit',       fa:'خروج سینمایی از صحنه',         en:'Cinematic exit', anim:'a-exit' },
      { cmd:'/freeze',     fa:'فریز کردن حرکت در لحظه خاص',  en:'Freeze frame moment', anim:'a-freeze' },
      { cmd:'/speedramp',  fa:'ترکیب حرکت آهسته و سریع',     en:'Slow-to-fast speed ramp', anim:'a-speedramp' },
      { cmd:'/bullettime', fa:'افکت آهسته سبک Bullet Time',  en:'Bullet Time slow effect', anim:'a-bullettime' },
      { cmd:'/floating',   fa:'حس شناور بودن در فضا',        en:'Floating in space', anim:'a-floating' },
      { cmd:'/falling',    fa:'صحنه سقوط دراماتیک',          en:'Dramatic falling', anim:'a-falling' },
    ]},
  { id:'g4', icon:'💡', fa:'نورپردازی سینمایی', en:'Cinematic Lighting',
    items:[
      { cmd:'/goldenhour', fa:'نور گرم ساعت طلایی',        en:'Golden hour warm light', anim:'a-goldenhour' },
      { cmd:'/bluehour',   fa:'نور سرد و آرام گرگ‌ومیش',    en:'Blue hour twilight', anim:'a-bluehour' },
      { cmd:'/neonlight',  fa:'نور نئونی سینمایی و زنده',  en:'Vivid neon lighting', anim:'a-neonlight' },
      { cmd:'/moody',      fa:'نور تیره و دراماتیک',       en:'Moody dramatic lighting', anim:'a-moody' },
      { cmd:'/softlight',  fa:'نور نرم و پخش‌شده استودیو', en:'Soft diffused studio light', anim:'a-softlight' },
      { cmd:'/rimlight',   fa:'نور حاشیه‌ای دور سوژه',     en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/silhouette', fa:'نمای قدرتمند سیلوئت',       en:'Strong silhouette', anim:'a-silhouette' },
      { cmd:'/spotlight',  fa:'نور متمرکز روی سوژه',       en:'Focused spotlight', anim:'a-spotlight' },
      { cmd:'/volumetric', fa:'پرتوهای حجمی اتمسفریک',     en:'Volumetric light beams', anim:'a-volumetric' },
      { cmd:'/backlight',  fa:'نور قوی از پشت سوژه',       en:'Strong backlight', anim:'a-backlight' },
      { cmd:'/nightscene', fa:'صحنه شب سینمایی و واقعی',   en:'Cinematic night scene', anim:'a-nightscene' },
    ]},
  { id:'g5', icon:'🖼️', fa:'ترکیب‌بندی و کادربندی', en:'Composition & Framing',
    items:[
      { cmd:'/wide',          fa:'کادر باز برای نمایش کامل صحنه',  en:'Wide full-scene frame', anim:'a-wide' },
      { cmd:'/tight',         fa:'کادر بسته برای تمرکز روی سوژه',  en:'Tight subject-focused frame', anim:'a-tight' },
      { cmd:'/minimal',       fa:'ترکیب‌بندی ساده و مینیمال',      en:'Minimal composition', anim:'a-minimal' },
      { cmd:'/leadinglines',  fa:'خطوط هدایت‌گر نگاه',             en:'Leading lines', anim:'a-leadinglines' },
      { cmd:'/ruleofthirds',  fa:'قانون یک‌سوم، کادر متعادل',       en:'Rule of thirds balance', anim:'a-ruleofthirds' },
      { cmd:'/symmetry',      fa:'ترکیب‌بندی متقارن',              en:'Symmetrical composition', anim:'a-symmetry' },
      { cmd:'/foreground',    fa:'پیش‌زمینه قوی برای عمق بیشتر',   en:'Strong foreground depth', anim:'a-foreground' },
      { cmd:'/framewithinframe', fa:'قاب طبیعی درون صحنه',         en:'Frame within a frame', anim:'a-framewithinframe' },
      { cmd:'/diagonal',      fa:'ترکیب‌بندی مورب و پویا',         en:'Diagonal dynamic composition', anim:'a-diagonal' },
      { cmd:'/centered',      fa:'قرارگیری سوژه در مرکز',          en:'Centered subject', anim:'a-centered' },
      { cmd:'/negativespace', fa:'استفاده مؤثر از فضای منفی',      en:'Effective negative space', anim:'a-negativespace' },
    ]},
  { id:'g6', icon:'✨', fa:'افکت‌های دوربین', en:'Camera Effects',
    items:[
      { cmd:'/motionblur', fa:'محوشدگی حرکت برای حس سرعت',  en:'Motion blur for speed', anim:'a-motionblur' },
      { cmd:'/zoomblur',   fa:'محوشدگی زوم دراماتیک',       en:'Dramatic zoom blur', anim:'a-zoomblur' },
      { cmd:'/bokeh',      fa:'بوکه در پس‌زمینه',           en:'Background bokeh', anim:'a-bokeh' },
      { cmd:'/lensflare',  fa:'فلر سینمایی لنز',            en:'Cinematic lens flare', anim:'a-lensflare' },
      { cmd:'/vignette',   fa:'تیره‌کردن لبه‌های تصویر',     en:'Vignette dark edges', anim:'a-vignette' },
      { cmd:'/splittone',  fa:'درجه‌بندی رنگی دوگانه',      en:'Split-tone grading', anim:'a-splittone' },
      { cmd:'/monochrome', fa:'تبدیل صحنه به سیاه‌وسفید',   en:'Monochrome black & white', anim:'a-monochrome' },
      { cmd:'/radialblur', fa:'محوشدگی شعاعی و پویا',       en:'Radial blur', anim:'a-radialblur' },
      { cmd:'/prism',      fa:'شکست نور منشوری',            en:'Prism light refraction', anim:'a-prism' },
      { cmd:'/glitch',     fa:'افکت گلیچ دیجیتال',          en:'Digital glitch effect', anim:'a-glitch' },
      { cmd:'/filmgrain',  fa:'دانه‌های فیلم با حس قدیمی',   en:'Vintage film grain', anim:'a-filmgrain' },
    ]},
  { id:'g7', icon:'🔍', fa:'فوکوس و عمق میدان', en:'Focus & Depth of Field',
    items:[
      { cmd:'/macro',         fa:'جزئیات بسیار نزدیک',          en:'Extreme macro detail', anim:'a-macro' },
      { cmd:'/shallowdepth',  fa:'عمق میدان کم',               en:'Shallow depth of field', anim:'a-shallowdepth' },
      { cmd:'/deepfocus',     fa:'وضوح پیش و پس‌زمینه',        en:'Deep focus, all sharp', anim:'a-deepfocus' },
      { cmd:'/selectivefocus',fa:'فوکوس روی سوژه، محو شدن اطراف',en:'Selective focus', anim:'a-selectivefocus' },
      { cmd:'/eyefocus',      fa:'فوکوس دقیق روی چشم‌ها',      en:'Sharp eye focus', anim:'a-eyefocus' },
      { cmd:'/centerfocus',   fa:'وضوح مرکز، محو شدن اطراف',   en:'Center focus, soft edges', anim:'a-centerfocus' },
      { cmd:'/tunnelfocus',   fa:'فوکوس تونلی برای جلب توجه',  en:'Tunnel focus', anim:'a-tunnelfocus' },
      { cmd:'/focusstack',    fa:'ترکیب چند فوکوس برای وضوح',  en:'Focus stacking sharpness', anim:'a-focusstack' },
      { cmd:'/dropfocus',     fa:'فوکوس روی قطره یا جزء خاص',  en:'Focus on a droplet detail', anim:'a-dropfocus' },
      { cmd:'/manualfocus',   fa:'کنترل دستی فوکوس',           en:'Manual focus control', anim:'a-manualfocus' },
      { cmd:'/bokehshape',    fa:'شکل‌دهی سفارشی نورهای بوکه', en:'Custom-shaped bokeh', anim:'a-bokehshape' },
    ]},
  { id:'g8', icon:'🎨', fa:'اصلاح و درجه‌بندی رنگ', en:'Color Correction & Grading',
    items:[
      { cmd:'/warm',        fa:'تن‌های گرم برای حس صمیمی',  en:'Warm tones, cozy feel', anim:'a-warm' },
      { cmd:'/cool',        fa:'تن‌های سرد برای حس آرام',   en:'Cool tones, calm feel', anim:'a-cool' },
      { cmd:'/contrast',    fa:'افزایش کنتراست تصویر',      en:'Increased contrast', anim:'a-contrast' },
      { cmd:'/exposure',    fa:'تنظیم روشنایی و نوردهی',    en:'Exposure adjustment', anim:'a-exposure' },
      { cmd:'/saturation',  fa:'افزایش یا کاهش غلظت رنگ',   en:'Color saturation control', anim:'a-saturation' },
      { cmd:'/desaturate',  fa:'کاهش رنگ برای ظاهر خنثی',   en:'Desaturated neutral look', anim:'a-desaturate' },
      { cmd:'/cinematic',   fa:'درجه‌بندی رنگ سینمایی',     en:'Cinematic color grading', anim:'a-cinematicgrade' },
      { cmd:'/tealorange',  fa:'رنگ‌بندی فیروزه‌ای و نارنجی',en:'Teal & orange grade', anim:'a-tealorange' },
      { cmd:'/vibrant',     fa:'تقویت رنگ‌ها، تصویر زنده‌تر',en:'Vibrant boosted colors', anim:'a-vibrant' },
      { cmd:'/bw',          fa:'تبدیل به سیاه‌وسفید',       en:'Black & white', anim:'a-bw' },
      { cmd:'/neon',        fa:'درجه‌بندی رنگ نئونی',       en:'Neon color grade', anim:'a-neon' },
    ]},
  { id:'g9', icon:'🧑‍🎤', fa:'پرتره و سوژه', en:'Portrait & Subject',
    items:[
      { cmd:'/portrait',       fa:'نمای پرتره',                   en:'Portrait shot', anim:'a-portrait' },
      { cmd:'/beauty',         fa:'تقویت زیبایی طبیعی و رنگ پوست',en:'Natural beauty enhance', anim:'a-beauty' },
      { cmd:'/rimlight',       fa:'نور حاشیه‌ای دور سوژه',        en:'Rim light around subject', anim:'a-rimlight' },
      { cmd:'/backgroundblur', fa:'محو شدن پس‌زمینه، برجستگی سوژه',en:'Blurred background, subject pop', anim:'a-backgroundblur' },
      { cmd:'/sharpfocus',     fa:'سوژه واضح و کاملاً شفاف',      en:'Razor-sharp subject', anim:'a-sharpfocus' },
      { cmd:'/monotone',       fa:'پرتره سیاه‌وسفید تک‌رنگ',      en:'Monotone B&W portrait', anim:'a-monotone' },
      { cmd:'/lowkey',         fa:'نورپردازی تیره و کم‌نور',      en:'Low-key dark lighting', anim:'a-lowkey' },
      { cmd:'/highkey',        fa:'نورپردازی روشن و پرنور',      en:'High-key bright lighting', anim:'a-highkey' },
      { cmd:'/closeup',        fa:'نمای نزدیک و پرجزئیات',       en:'Close-up portrait', anim:'a-closeup' },
      { cmd:'/fullbody',       fa:'نمایش تمام‌قد سوژه',           en:'Full-body shot', anim:'a-fullbody' },
      { cmd:'/candid',         fa:'لحظه طبیعی و بدون ژست',       en:'Candid natural moment', anim:'a-candid' },
    ]},
];

/* ---- 2) Anatomy sections ----------------------------------- */
/* chips: { en = prompt text, fa = Persian meaning for summary } */
const ANATOMY = [
  { id:'subject', icon:'🎯', fa:'موضوع', en:'Subject',
    question:{ fa:'تصویرت قراره نشون بده چی رو؟', en:'What should the image show?' },
    hint:{ fa:'اصلی‌ترین چیز تصویر — همون اول نوشته میشه', en:'The main subject — written first' },
    placeholders:['a Persian warrior riding a horse','a futuristic city at night','a woman in a red dress'],
    chips:[
      {en:'a lone traveler', fa:'یک مسافر تنها'},
      {en:'a majestic lion', fa:'شیری باشکوه'},
      {en:'a futuristic city', fa:'شهر آینده‌نگرانه'},
      {en:'a cozy coffee shop', fa:'یک کافه دنج'},
      {en:'a dragon over mountains', fa:'اژدهایی بالای کوه‌ها'},
      {en:'a child with a kite', fa:'کودکی با بادبادک'},
    ]},
  { id:'medium', icon:'🖌️', fa:'رسانه', en:'Medium',
    question:{ fa:'با چه سبک و ابزاری کشیده بشه؟', en:'Drawn with what medium?' },
    hint:{ fa:'نقاشی، عکس، رندر ۳بعدی یا...؟', en:'Painting, photo, 3D or...?' },
    placeholders:['oil painting','photograph','3D render'],
    chips:[
      {en:'oil painting', fa:'نقاشی روغن'},
      {en:'photograph', fa:'عکس واقعی'},
      {en:'3D render', fa:'رندر سه‌بعدی'},
      {en:'watercolor', fa:'آبرنگ'},
      {en:'digital art', fa:'نقاشی دیجیتال'},
      {en:'pencil sketch', fa:'طرح مدادی'},
      {en:'concept art', fa:'کانسپت آرت'},
      {en:'anime style', fa:'سبک انیمه'},
      {en:'pixel art', fa:'پیکسل آرت'},
      {en:'clay model', fa:'مجل سفالی'},
    ]},
  { id:'style', icon:'🎭', fa:'سبک', en:'Style',
    question:{ fa:'حال‌وهوای تصویر چی باشه؟', en:'What mood and style?' },
    hint:{ fa:'فضای کلی کار: حماسی، تاریک، بازیگوش...', en:'Overall mood: epic, dark, playful...' },
    placeholders:['epic fantasy','cyberpunk','minimalist'],
    chips:[
      {en:'epic fantasy', fa:'فانتزی حماسی'},
      {en:'cyberpunk', fa:'سایبرپانک'},
      {en:'minimalist', fa:'مینیمال'},
      {en:'steampunk', fa:'استیم‌پانک'},
      {en:'surrealism', fa:'سوررئال'},
      {en:'art deco', fa:'آرت دکو'},
      {en:'vaporwave', fa:'ویپورویو'},
      {en:'gothic', fa:'گوتیک'},
      {en:'studio ghibli style', fa:'سبک استودیو جیبلی'},
      {en:'photorealistic', fa:'فتورئالیست'},
    ]},
  { id:'artist', icon:'👨‍🎨', fa:'هنرمند', en:'Artist',
    question:{ fa:'به سبک کدوم هنرمند باشه؟', en:'In which artist\'s style?' },
    hint:{ fa:'الان میشه گفت اختیاریه', en:'Optional — you can skip' },
    placeholders:['by Greg Rutkowski','in the style of Van Gogh'],
    chips:[
      {en:'by Greg Rutkowski', fa:'به سبک گرگ روتکوفسکی'},
      {en:'in the style of Van Gogh', fa:'به سبک ون‌گوگ'},
      {en:'by Alphonse Mucha', fa:'به سبک آلفونس موشا'},
      {en:'by Beeple', fa:'به سبک بیپل'},
      {en:'by H.R. Giger', fa:'به سبک اچ‌آر گیگر'},
      {en:'by Hayao Miyazaki', fa:'به سبک هایائو میازاکی'},
      {en:'by Frank Frazetta', fa:'به سبک فرانک فرازتا'},
      {en:'by Moebius', fa:'به سبک موبیوس'},
    ]},
  { id:'website', icon:'🌐', fa:'سایت', en:'Website',
    question:{ fa:'از کدوم سایتِ الهام‌بخش باشه؟', en:'Inspired by which site?' },
    hint:{ fa:'کلمه‌ای که کیفیت رو می‌ره بالا', en:'A keyword that boosts quality' },
    placeholders:['ArtStation trending','deviantart'],
    chips:[
      {en:'ArtStation trending', fa:'ترند آرت‌استیشن'},
      {en:'trending on ArtStation', fa:'پرطرفدارِ آرت‌استیشن'},
      {en:'deviantart masterpiece', fa:'شاهکارِ دیویانت‌آرت'},
      {en:'Pixiv top rated', fa:'برترین‌های پیکسیو'},
      {en:'Behance featured', fa:'منتخبِ بیهانس'},
      {en:'CGSociety', fa:'انجمن CGSociety'},
    ]},
  { id:'resolution', icon:'🖼️', fa:'کیفیت', en:'Resolution',
    question:{ fa:'کیفیت و جزئیات چقدر باشه؟', en:'How detailed?' },
    hint:{ fa:'هرچی بالاتر، پرجزئیات‌تر', en:'Higher = more detail' },
    placeholders:['8K','highly detailed'],
    chips:[
      {en:'8K', fa:'کیفیت ۸K'},
      {en:'4K', fa:'کیفیت ۴K'},
      {en:'ultra HD', fa:'فول‌اچ‌دی'},
      {en:'highly detailed', fa:'بسیار پرجزئیات'},
      {en:'sharp focus', fa:'فوکوس تیز'},
      {en:'masterpiece', fa:'شاهکار'},
      {en:'best quality', fa:'بهترین کیفیت'},
      {en:'hyper-detailed', fa:'فوق‌جزئیات'},
      {en:'unreal engine 5 render', fa:'رندر آنریل انجین ۵'},
      {en:'octane render', fa:'رندر اکتین'},
    ]},
  { id:'details', icon:'🔎', fa:'جزئیات', en:'Details',
    question:{ fa:'چه جزئیاتی توی تصویر باشه؟', en:'Which details?' },
    hint:{ fa:'لباس، هوا، اشیاء، حالت و...', en:'Clothes, weather, objects, pose...' },
    placeholders:['glowing armor, flowing cape','rain on the streets'],
    chips:[
      {en:'glowing armor and flowing cape', fa:'زره درخشان و شنلِ بال‌کشنده'},
      {en:'rain-soaked streets', fa:'خیابان‌های خیس باران'},
      {en:'flying petals', fa:'گلبرگ‌های در حال پرواز'},
      {en:'swirling dust particles', fa:'ذرات غبار چرخان'},
      {en:'intricate jewelry', fa:'جواهرات ظریف'},
      {en:'dramatic pose', fa:'ژست دراماتیک'},
      {en:'wind-blown hair', fa:'موی وزیده با باد'},
      {en:'neon signs reflection', fa:'انعکاس نور نئون'},
    ]},
  { id:'color', icon:'🌈', fa:'رنگ', en:'Color',
    question:{ fa:'پالت رنگی چی باشه؟', en:'Which color palette?' },
    hint:{ fa:'رنگ‌های غالب تصویر', en:'The dominant colors' },
    placeholders:['gold and crimson','muted colors'],
    chips:[
      {en:'gold and crimson', fa:'طلایی و قرمز'},
      {en:'vibrant colors', fa:'رنگ‌های زنده'},
      {en:'muted colors', fa:'رنگ‌های محو'},
      {en:'pastel palette', fa:'پالت پاستلی'},
      {en:'monochrome', fa:'تک‌رنگ'},
      {en:'neon blue and pink', fa:'نئونی آبی و صورتی'},
      {en:'earthy tones', fa:'تن‌های خاکی'},
      {en:'black and gold', fa:'مشکی و طلایی'},
    ]},
  { id:'lighting', icon:'💡', fa:'نورپردازی', en:'Lighting',
    question:{ fa:'نورپردازی چطور باشه؟', en:'What kind of lighting?' },
    hint:{ fa:'نوع و جهت نور — روحِ تصویر', en:'Light type and direction' },
    placeholders:['cinematic lighting','golden hour'],
    chips:[
      {en:'cinematic lighting', fa:'نورپردازی سینمایی'},
      {en:'golden hour', fa:'ساعت طلایی'},
      {en:'studio lighting', fa:'نور استودیویی'},
      {en:'soft diffused light', fa:'نور نرم و پخش'},
      {en:'dramatic shadows', fa:'سایه‌های دراماتیک'},
      {en:'volumetric lighting', fa:'نورپردازی حجمی'},
      {en:'backlit', fa:'نور از پشت'},
      {en:'neon glow', fa:'درخشش نئونی'},
      {en:'natural sunlight', fa:'نور طبیعی خورشید'},
    ]},
];

/* ---- 3) Default negative prompt ---------------------------- */
const NEGATIVE_DEFAULTS = [
  'blurry','low quality','deformed','extra fingers','bad anatomy',
  'watermark','text','ugly','duplicate','mutated hands',
  'disfigured','bad proportions','lowres','jpeg artifacts','oversaturated'
];

/* ---- 4) UI translations ------------------------------------ */
const I18N = {
  fa:{
    dir:'rtl', lang:'فارسی',
    title:'پرامپت‌فورج', sub:'آهنگریِ پرامپت حرفه‌ای برای هوش مصنوعی',
    step:'مرحله', of:'از', next:'بعدی ←', back:'→ قبلی', skip:'رد شدن', finish:'🎯 ساختن پرامپت',
    modeImg:'🖼 تصویر', modeVid:'🎬 ویدیو', modeFast:'⚡ ترکیبی',
    modeQ:'می‌خوای پرامپت رو برای چی بسازی؟',
    shotQ:'دستورات دوربین و افکت — هرچی خواستی انتخاب کن',
    shotHint:'برای ویدیو/ترکیبی. می‌تونی چندتا رو با هم انتخاب کنی',
    paramsQ:'تنظیمات فنی (اختیاری)',
    finalTitle:'✅ پرامپتِ آماده‌ست!',
    summaryTitle:'📖 این پرامپت چی میگه؟',
    negativeTitle:'پرامپت منفی — چیزهایی که نمی‌خوام',
    copy:'📋 کپی پرامپت', copied:'✅ کپی شد!', copySummary:'📋 کپی خلاصه',
    save:'💾 ذخیره', restart:'🔄 از نو', surprise:'🎲 سورپرایزم کن!',
    history:'تاریخچه', historyEmpty:'هنوز چیزی ذخیره نشده.',
    weight:'وزن', boost:'＋', reduce:'－',
    steps:'Steps', cfg:'CFG', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'کپی', delHistory:'حذف', emptyHistory:'خالی‌کردن همه',
    footer:'ساخته‌شده با ❤ برای پرامپت‌نویسان',
    switchLang:'🇬🇧 English',
    customPh:'یا خودت بنویس...',
    selected:'انتخاب‌شده‌ها',
  },
  en:{
    dir:'ltr', lang:'English',
    title:'Prompt-Forge', sub:'Professional prompt blacksmithing for AI',
    step:'Step', of:'of', next:'Next →', back:'← Back', skip:'Skip', finish:'🎯 Build prompt',
    modeImg:'🖼 Image', modeVid:'🎬 Video', modeFast:'⚡ Hybrid',
    modeQ:'What are you building a prompt for?',
    shotQ:'Camera & effect commands — pick what you want',
    shotHint:'For video/hybrid. You can pick several.',
    paramsQ:'Technical settings (optional)',
    finalTitle:'✅ Your prompt is ready!',
    summaryTitle:'📖 What does it mean?',
    negativeTitle:'Negative prompt — what you DON\'T want',
    copy:'📋 Copy prompt', copied:'✅ Copied!', copySummary:'📋 Copy summary',
    save:'💾 Save', restart:'🔄 Restart', surprise:'🎲 Surprise me!',
    history:'History', historyEmpty:'Nothing saved yet.',
    weight:'weight', boost:'＋', reduce:'－',
    steps:'Steps', cfg:'CFG', sampler:'Sampler', ar:'Aspect Ratio', seed:'Seed',
    copyPrompt:'Copy', delHistory:'Delete', emptyHistory:'Clear all',
    footer:'Made with ❤ for prompt engineers',
    switchLang:'🇮🇷 فارسی',
    customPh:'or type your own...',
    selected:'Selected',
  }
};

const SAMPLERS = ['DPM++ 2M Karras','Euler a','DDIM','DPM++ SDE','UniPC','Heun'];
const ASPECTS  = ['1:1','16:9','9:16','4:3','3:2','21:9'];
